### ISSUE TITLE
rem适配移动设备

### ISSUE THREAD

**Issue by yanyue404** [yanyue404/blog#39]
## 前言

移动端 rem 适配方案回顾总结

## 如何使用 rem

`rem` 单位的计算参考 html 的根节点 `font-size`进行计算，根节点的字体变化，布局参考的 rem 页面也会相应进行缩放，此为 rem 布局的本质。

### 1. 动态改变 html 的 font-size 值

几乎在每个浏览器中我们都将 `html` 的 `font-size` 初始化 为 **16px** ， 我们动态改变的话可以暂时将 `16px` 设置为 rem 适配的根节点 `font-size` 初始值。

那么如何进行适配动态修改？

假设设计稿宽度 为 750px，我们定义了自己使用 1rem = 16px 的单位去布局，如何适配呢？

在 chrome 的 手机 iphone 模拟器宽度为 `375px`，正好为设计稿的 一半，我们可以口算: 当时的 1rem 应该等于初始化时 html 节点 `font-size` 的一半,即 `newFontSize = 16/2 = 8px`,这样一半对一半不就适配了吗...

从中得到公式 `设计稿宽度/16px = 需要适配的设备宽度/8px`,能够看出 新的 `font-size` 是参考 当前的设备宽度与原设计稿的宽度，进行等比缩放的

最终得到 `newFontSize = 16px * 需要适配的设备宽度 / 原设计稿宽度`

```js
(function(doc, win) {
  var resizeEvt =
      "orientationchange" in window ? "orientationchange" : "resize",
    setRemResponse = function() {
      var vM = 750;
      var vfontSize = 16;
      var html = doc.documentElement;
      var newfontSize = (vfontSize * html.clientWidth) / vM;
      html.style.fontSize = newfontSize + "px";
    };
  doc.addEventListener("DOMContentLoaded", setRemResponse, false);
  win.addEventListener(resizeEvt, setRemResponse, false);
})(document, window);
```

### 2. 实际使用

将测量得出的`btn` 按钮的样式从 `px`转换 为 `rem`

```css
.btn {
  width: 699px; /* 699/16 => 43.6875rem; */
  height: 90px; /* 90/16px => 5.625rem;  */
  background: rgba(90, 173, 246, 1);
  border-radius: 6px; /* 6/16=> 0.375rem; */
}
```

自己计算太繁琐，使用 scss 定义 函数代替计算过程

```Scss
@function pxToRem($initialStyle) {
  @return $initialStyle/16 * 1rem;
}
```

那么上面的 `css`改写为:

```Scss
.btn {
  width: pxToRem(699);
  height:pxToRem(90);
  background: rgba(90, 173, 246, 1);
  border-radius:pxToRem(6);
}
```

> 补充： vscode 的插件 [cssrem](https://marketplace.visualstudio.com/items?itemName=cipchk.cssrem) 支持计算 将我们在 css,scss 中输入的 px 转换为 rem 单位，默认设置的 font-size 为 **16px**

### 1. 简单分析

分析上一节我们最终得到 `newFontSize = 16px * 需要适配的设备宽度 / 原设计稿宽度`

每次计算要除以 100 很是繁琐，我们若将 初始的 html 根节点 `font-size`变为方便计算的，反正它最终做为一个除数，变为多少呢? 是否 **100** 更为方便呢？对了！

```js
const oHtml = document.documentElement;
const clientWidth = oHtml.clientWidth;
var vM = 750;
var vfontSize = 100;
// 移动设备
oHtml.style.fontSize = (vfontSize * clientWidth) / vM + "px";
```

### 2. 实际使用

还是上面熟悉的那个 `btn`, 将`px`转换 为 `rem`, 口算得出结果。

```css
.btn {
  width: 699px; /* 699/100 => 6.99rem; */
  height: 90px; /* 90/100 => 0.9rem;  */
  background: rgba(90, 173, 246, 1);
  border-radius: 6px; /* 6/100=> 0.06rem; */
}
```

不得不说，有了 scss 是真的方便！

```Scss
@function reduced100($initialStyle) {
  @return $initialStyle/100 * 1rem;
}
```

那么上面的 `css`函数方法改写为:

```Scss
.btn {
  width: reduced100(699);
  height:reduced100(90);
  background: rgba(90, 173, 246, 1);
  border-radius:reduced100(6);
}
```

怎么样，`rem` 原来就是这么简单！！！

## 工具函数

上面的方法，二选其一就可以了，毕竟现在 `javascript` 的 执行效率不差！

```js
(function(doc, win) {
  var resizeEvt =
      "orientationchange" in window ? "orientationchange" : "resize",
    setRemResponse = function() {
      var vM = 750;
      var vfontSize = 16;
      var html = doc.documentElement;
      var newfontSize = (vfontSize * html.clientWidth) / vM;
      html.style.fontSize = newfontSize + "px";
    };
  doc.addEventListener("DOMContentLoaded", setRemResponse, false);
  win.addEventListener(resizeEvt, setRemResponse, false);
})(document, window);
```

## 纯 CSS 适配方案：font-size: 100vw / 7.5

**与 JS rem 适配方案不完全相同，但非常接近，在绝大多数手机场景下可以认为效果几乎一样。**

两种写法在**常见手机屏幕宽度范围（约320–480px）**内的表现差异非常小，通常肉眼和实际使用都难以察觉区别。

### 核心对比（以设计稿750px为例）

| 屏幕宽度 | JS rem 方案 (html font-size) | html { font-size: 13.333333vw } | 差距 |
|----------|-------------------------------|-----------------------------------|------|
| 750px    | 16px                          | ≈100px / 7.5 ≈ 13.333vw → 100px   | 0px  |
| 414px    | ≈8.83px                       | 414 × 13.333vw / 100 ≈ 55.2px     | ≈0.03px |
| 375px    | 8px                           | 375 × 13.333vw / 100 = 50px       | 0px  |
| 360px    | ≈7.68px                       | 360 × 13.333vw / 100 = 48px       | ≈0.01px |
| 320px    | ≈6.827px                      | 320 × 13.333vw / 100 = 42.667px   | ≈0.01px |

### 结论：二选一推荐

**推荐使用：html { font-size: 13.333333vw; }**  
（或者更精确写成 `font-size: 13.3333333333vw;` 或 `font-size: 100vw / 7.5;`）

**理由排名（从最重要到次要）：**

1. **实现更简单**，一行 CSS 搞定，无需 JS
2. **零运行时开销**，浏览器直接计算，不依赖 DOMContentLoaded
3. **响应更快**（尤其是旋转屏幕时）
4. **兼容性很好**（现代手机浏览器全部支持 vw 单位）
5. **在主流手机宽度下与 JS rem 方案的误差极小**（<0.1px）

**什么时候还考虑用 JS rem 方案？**

- 必须兼容非常老的浏览器（基本可以忽略了，2025-2026 年基本无此需求）
- 项目里已经有一套完整的基于 JS 的 rem + flexible 方案（不想改动现有体系）
- 需要做一些 vw 无法满足的**额外逻辑**（比如设置最大/最小 font-size 阈值）

正常新项目或想简化代码的情况下，**直接用 vw** 就够了，效果几乎一致，但写法和维护成本低很多。

一句话总结：  

**能用 vw 就用 vw，JS rem 已经是上一代的做法了。**

### 推荐 reset.css

利用媒体查询控制屏幕适配的最小宽度。

```css
html{color:#000;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;height:100%;font-family:PingFangSC-Regular,PingFang SC,sans-serif;-webkit-touch-callout:none;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;font-size:13.3333333333vw}
body{line-height:1.5;font-size:.28rem;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;margin:0 auto!important}
article,aside,blockquote,body,button,code,dd,details,div,dl,dt,fieldset,figcaption,figure,footer,form,h1,h2,h3,h4,h5,h6,header,hgroup,hr,input,legend,li,menu,nav,ol,p,pre,section,td,textarea,th,ul{margin:0;padding:0;outline:0;-webkit-tap-highlight-color:transparent;-webkit-box-sizing:border-box;box-sizing:border-box}
h1,h2,h3,h4,h5,h6{font-weight:500}
.clearfix:after,.clearfix:before{content:" ";display:table;height:0;visibility:hidden}
.clearfix:after{clear:both}
a,img,input{-webkit-tap-highlight-color:transparent}
input{-webkit-user-modify:read-write-plaintext-only;border:0;outline:medium}
input,option,select,textarea{font-size:100%;font-family:inherit;-webkit-appearance:none}
table{border-collapse:collapse;border-spacing:0}
fieldset,img{border:0 none}
address,caption,cite,code,dfn,em,th,var{font-style:normal;font-weight:500}
li,ol,ul{list-style:none}
a,ins{text-decoration:none}mark{background:0 0}textarea{resize:none}
img{display:block;margin:0;padding:0;width:100%}a{text-decoration:none}b,em,i,li{font-style:normal!important}
@media screen and (min-width:540px){
    html{font-size:72Px!important}
    body{width:540Px}
}
```

### postcss-pxtorem 转换 px 适配 rem

vite4 + postcss-pxtorem@6

```
{
   css:  {
          postcss: {
            plugins: [
              pxtorem({
                rootValue({ file }: any) {
                  if (file.indexOf('sprite') !== -1) {
                    return 100
                  }
                  return file.indexOf('vant') !== -1 ? 50 : 100
                },
                selectorBlackList: [], // 忽略转换正则匹配项
                propList: ['*']
              })
            ]
          },
          preprocessorOptions: {
            scss: {
              additionalData: `@import "./src/assets/sprite/sprite.scss";@import "./src/assets/scss/variable.scss";`
            }
          }
        }
}

```
